[versions]
gson = "+"
json = "+"
junit = "+"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
json = { group = "org.json", name = "json", version.ref = "json" }
# > Required -- JUnit 4 framework
# https://developer.android.com/training/testing/local-tests#dependencies
junit = { group = "junit", name = "junit", version.ref = "junit" }
